function riskyOperation () {
    if (Math.random () < 0.5){
        throw new Error ('Task failed!');
    }

    return 'Task successful!'
}

try {

    const result = riskyOperation ();
    console.log (result);

} catch (ex) {
    console.error (ex.message);
}
